<a href="https://colab.research.google.com/github/GKSJ-AI-CliniScan/MedAssistAI/blob/TahuraShaikh/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [ ]:
dataset = pd.read_csv("/content/dataset2_training.csv")

print(dataset.shape)
dataset.head()

(60000, 378)

,Disease,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,Coronary Atherosclerosis,0,0,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,Cholecystitis,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Osteoarthritis,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Vaginal Yeast Infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Concussion,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
X = dataset.drop("Disease", axis=1)
y = dataset["Disease"]

print("Features:", X.shape)
print("Labels:", y.shape)

Features: (60000, 377)
Labels: (60000,)

In [ ]:
encoder = LabelEncoder()

y = encoder.fit_transform(y)

print("Total Diseases:", len(np.unique(y)))

Total Diseases: 658

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(48000, 377)
(12000, 377)

In [ ]:
start = time.time()

dt = DecisionTreeClassifier(
    random_state=42
)

dt.fit(X_train, y_train)

end = time.time()

In [ ]:
y_pred = dt.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

print("Decision Tree Accuracy :", accuracy)
print("Precision :", precision)
print("Recall :", recall)
print("F1 Score :", f1)
print("Training Time :", round(end-start,2),"seconds")

Decision Tree Accuracy : 0.7388333333333333
Precision : 0.7476517675166563
Recall : 0.7388333333333333
F1 Score : 0.7381599876925804
Training Time : 6.99 seconds

In [ ]:
print(classification_report(
    y_test,
    y_pred,
    zero_division=0
))

              precision    recall  f1-score   support

           0       0.60      1.00      0.75         3
           1       0.89      1.00      0.94        17
           2       0.54      0.70      0.61        10
           4       0.80      0.80      0.80        10
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.25      0.50      0.33         2
           8       0.43      0.47      0.45        19
           9       0.65      0.59      0.62        51
          10       0.82      0.89      0.86        76
          11       0.69      0.69      0.69        77
          12       0.49      0.53      0.51        51
          13       0.33      0.33      0.33         9
          14       0.82      0.90      0.86        51
          15       0.49      0.56      0.52        34
          16       0.79      0.84      0.82        77
          17       0.75      0.95      0.84        19
          18       0.78      0.73      0.75        52
          19       0.92      0.67      0.77        51
          20       1.00      0.50      0.67         2
          21       0.67      0.90      0.77        20
          22       0.00      0.00      0.00         1
          23       0.70      0.95      0.81        20
          24       0.46      0.60      0.52        10
          25       0.83      0.88      0.85        33
          26       0.50      0.83      0.62         6
          27       0.90      0.75      0.82        51
          28       0.00      0.00      0.00         1
          29       0.86      0.55      0.67        11
          30       0.62      0.73      0.67        11
          31       1.00      1.00      1.00         1
          32       1.00      1.00      1.00         1
          33       0.64      0.78      0.70         9
          34       1.00      1.00      1.00         1
          35       0.78      0.70      0.74        10
          36       1.00      1.00      1.00         2
          38       0.25      1.00      0.40         1
          39       0.84      0.92      0.88        52
          40       0.63      0.63      0.63        30
          41       0.86      0.95      0.90        76
          42       0.82      0.78      0.80        18
          43       0.64      0.78      0.70         9
          44       0.67      1.00      0.80         2
          45       0.69      0.80      0.75        51
          46       0.62      0.62      0.62         8
          47       0.89      0.87      0.88        77
          48       0.50      1.00      0.67         1
          49       0.75      0.82      0.78        11
          50       0.62      0.65      0.64        52
          51       0.50      0.50      0.50        10
          52       0.50      0.50      0.50         2
          53       0.24      0.55      0.33        11
          54       0.00      0.00      0.00         1
          55       0.17      0.25      0.20         4
          56       1.00      0.88      0.93         8
          57       0.45      0.72      0.55        18
          58       0.44      0.70      0.54        10
          59       1.00      1.00      1.00         1
          60       0.61      0.70      0.65        20
          61       0.70      0.74      0.72        19
          62       1.00      1.00      1.00         1
          64       0.85      0.89      0.87        19
          65       0.79      0.88      0.83        34
          66       0.67      0.33      0.44         6
          67       0.94      0.94      0.94        18
          68       0.90      0.87      0.89        76
          69       0.84      0.82      0.83        33
          70       0.51      0.59      0.55        34
          71       1.00      0.75      0.86         4
          72       0.23      0.32      0.27        19
          73       0.57      0.80      0.67        10
          74       0.66      0.73      0.69        51
          75       0.25      1.00      0.40         1
          76       0.56      0.83      0.67         6
          77       1.00      1.00      1.00         1
          78       0.74      0.81      0.77        52
          79       0.67      0.44      0.53         9
          80       0.00      0.00      0.00         0
          81       0.00      0.00      0.00         1
          82       0.95      1.00      0.98        20
          83       0.67      0.40      0.50         5
          84       0.00      0.00      0.00         1
          85       1.00      0.50      0.67         2
          86       0.96      0.91      0.93        77
          87       0.46      0.60      0.52        20
          88       0.00      0.00      0.00         2
          89       0.45      0.50      0.48        10
          90       0.55      0.60      0.57        10
          91       0.86      0.85      0.85        52
          92       0.45      0.68      0.54        31
          93       0.25      0.33      0.29         3
          94       0.80      1.00      0.89         4
          95       0.00      0.00      0.00         1
          96       1.00      0.50      0.67         2
          97       0.00      0.00      0.00         2
          98       1.00      0.67      0.80         3
          99       1.00      1.00      1.00         2
         100       0.00      0.00      0.00         1
         101       0.50      0.50      0.50        12
         102       0.89      0.76      0.82        33
         103       1.00      0.50      0.67         2
         104       0.50      0.67      0.57         3
         105       0.81      0.75      0.78        76
         106       0.93      0.72      0.81        18
         108       0.33      0.50      0.40         2
         109       0.17      1.00      0.29         1
         110       0.90      0.88      0.89        51
         111       0.72      0.73      0.72        52
         112       0.62      0.64      0.63        33
         114       0.00      0.00      0.00         1
         115       0.70      0.70      0.70        10
         116       0.55      0.69      0.61        51
         117       0.81      0.88      0.84        33
         118       0.71      0.67      0.69        33
         119       0.70      0.78      0.74         9
         120       0.50      0.60      0.55         5
         121       0.78      0.78      0.78        32
         122       0.69      0.90      0.78        10
         123       1.00      0.50      0.67         2
         124       1.00      0.60      0.75         5
         125       0.89      0.73      0.80        11
         126       1.00      1.00      1.00         1
         127       0.76      0.90      0.82        52
         128       0.77      0.73      0.75        77
         129       0.97      0.92      0.95        75
         130       0.78      0.85      0.81        33
         131       0.92      0.71      0.80        31
         132       0.00      0.00      0.00         1
         134       0.83      0.85      0.84        52
         135       0.82      0.90      0.86        77
         136       0.00      0.00      0.00         3
         137       0.72      0.64      0.68        33
         138       0.64      0.71      0.67        52
         140       0.64      0.73      0.68        52
         141       0.33      0.58      0.42        19
         142       0.42      0.48      0.45        33
         143       0.75      1.00      0.86         6
         144       0.73      0.73      0.73        11
         145       0.77      0.59      0.67        17
         146       0.75      0.71      0.73        51
         147       0.50      1.00      0.67         2
         149       0.00      0.00      0.00         1
         150       0.00      0.00      0.00         1
         151       0.69      0.74      0.71        77
         152       0.60      0.75      0.67         4
         153       1.00      1.00      1.00         1
         154       0.43      0.50      0.46         6
         155       0.64      0.73      0.68        51
         156       0.72      0.72      0.72        29
         157       0.58      0.64      0.61        11
         158       0.82      0.89      0.85        75
         159       0.70      0.72      0.71        53
         160       0.59      0.68      0.63        19
         161       0.78      0.90      0.84        52
         162       0.82      0.87      0.84        31
         163       0.90      0.82      0.86        33
         164       0.83      0.79      0.81        19
         165       0.17      0.21      0.19        19
         166       0.92      0.92      0.92        51
         167       0.00      0.00      0.00         1
         168       0.50      0.75      0.60         4
         169       0.50      1.00      0.67         1
         170       0.67      1.00      0.80         2
         171       0.00      0.00      0.00         1
         172       0.00      0.00      0.00         1
         173       0.00      0.00      0.00         1
         174       0.70      0.74      0.72        77
         175       0.68      0.64      0.66        33
         176       0.00      0.00      0.00         2
         177       0.60      0.83      0.69        30
         178       0.00      0.00      0.00         2
         179       0.31      0.29      0.30        14
         180       0.80      0.40      0.53        10
         181       0.50      0.65      0.56        31
         182       0.83      0.83      0.83         6
         183       0.92      0.86      0.89        51
         184       0.57      0.67      0.62         6
         185       0.54      0.42      0.47        50
         186       1.00      0.50      0.67         2
         187       0.79      0.75      0.77        20
         188       0.87      0.87      0.87        52
         189       0.79      0.76      0.78        34
         190       0.94      0.89      0.92        19
         191       0.60      0.82      0.69        11
         192       0.00      0.00      0.00         1
         193       0.67      0.75      0.71        76
         195       0.00      0.00      0.00         2
         196       0.20      0.50      0.29         2
         197       0.00      0.00      0.00         2
         198       0.00      0.00      0.00         1
         199       0.76      0.76      0.76        17
         200       1.00      1.00      1.00         2
         201       0.81      0.68      0.74        19
         202       0.00      0.00      0.00         0
         203       1.00      0.70      0.82        20
         204       0.33      0.25      0.29         4
         205       0.66      0.83      0.74        30
         206       0.00      0.00      0.00         1
         207       0.00      0.00      0.00         1
         208       0.85      0.88      0.87        77
         209       1.00      0.80      0.89         5
         210       0.88      0.82      0.85        51
         211       0.67      1.00      0.80         2
         212       0.94      0.94      0.94        18
         213       1.00      0.80      0.89         5
         214       0.00      0.00      0.00         1
         215       1.00      0.33      0.50         3
         217       0.51      0.66      0.58        32
         218       0.00      0.00      0.00         1
         219       0.00      0.00      0.00         1
         220       0.63      0.67      0.65        33
         221       0.62      0.73      0.67        11
         222       0.00      0.00      0.00         1
         223       0.74      0.78      0.76        18
         224       0.00      0.00      0.00         1
         225       0.20      0.10      0.13        10
         226       0.00      0.00      0.00         3
         227       0.67      0.50      0.57         4
         228       0.00      0.00      0.00         2
         229       0.62      0.92      0.74        25
         230       0.80      0.67      0.73        18
         231       0.00      0.00      0.00         1
         232       0.00      0.00      0.00         1
         233       0.50      0.33      0.40         6
         234       1.00      1.00      1.00         2
         235       0.76      0.74      0.75        34
         236       0.00      0.00      0.00         1
         237       0.00      0.00      0.00         2
         238       0.75      0.60      0.67         5
         239       0.92      0.92      0.92        50
         240       1.00      1.00      1.00         5
         241       1.00      1.00      1.00         1
         242       0.71      0.50      0.59        10
         243       0.72      0.70      0.71        77
         244       0.59      0.76      0.67        34
         245       0.00      0.00      0.00         1
         246       0.61      0.71      0.65        51
         247       1.00      0.91      0.95        34
         248       0.64      0.70      0.67        33
         249       0.74      0.76      0.75        33
         250       0.62      0.42      0.50        19
         251       0.80      0.86      0.83        77
         252       0.40      0.40      0.40         5
         253       1.00      0.80      0.89         5
         254       0.25      1.00      0.40         1
         255       0.67      0.60      0.63        20
         256       0.20      1.00      0.33         1
         257       1.00      0.67      0.80         3
         258       0.82      0.92      0.87        77
         259       0.80      0.67      0.73         6
         260       0.00      0.00      0.00         1
         261       0.74      0.82      0.78        51
         262       0.60      0.75      0.67         4
         263       0.00      0.00      0.00         1
         264       0.80      0.73      0.76        11
         265       0.43      0.38      0.40         8
         266       0.20      0.20      0.20         5
         267       0.91      0.80      0.85        51
         268       0.74      0.77      0.75        30
         269       0.93      0.79      0.85        52
         270       0.75      0.33      0.46         9
         271       0.74      0.76      0.75        33
         273       0.00      0.00      0.00         1
         274       0.76      0.80      0.78        20
         275       0.00      0.00      0.00         1
         276       0.00      0.00      0.00         1
         277       0.88      0.88      0.88        52
         278       0.00      0.00      0.00         1
         279       0.82      0.90      0.86        10
         280       0.63      0.60      0.61        52
         281       0.81      0.89      0.85        19
         282       0.82      0.87      0.84        52
         283       0.33      0.50      0.40         2
         285       0.00      0.00      0.00         1
         286       0.50      1.00      0.67         1
         287       0.33      0.44      0.38         9
         288       0.33      0.20      0.25         5
         289       0.47      0.70      0.56        10
         290       0.00      0.00      0.00         0
         291       0.00      0.00      0.00         1
         292       0.90      0.85      0.87        52
         293       1.00      1.00      1.00         1
         294       0.90      0.84      0.87        32
         295       0.00      0.00      0.00         1
         296       1.00      0.50      0.67         2
         297       1.00      1.00      1.00         2
         298       0.95      0.78      0.86        51
         299       0.00      0.00      0.00         1
         300       0.93      0.92      0.93        77
         301       0.62      0.72      0.67        25
         302       0.90      0.95      0.93        20
         304       0.00      0.00      0.00         2
         305       0.79      0.83      0.81        18
         306       0.79      0.83      0.81        18
         307       0.73      0.83      0.78        53
         308       0.00      0.00      0.00         1
         309       0.74      0.71      0.73        52
         310       0.00      0.00      0.00         2
         311       0.81      0.75      0.78        51
         312       0.70      0.78      0.74        18
         313       0.84      0.94      0.89        33
         314       0.44      0.36      0.40        11
         315       0.67      0.78      0.72        18
         316       0.70      0.70      0.70        10
         318       0.64      0.64      0.64        77
         319       0.93      0.90      0.92        30
         320       0.69      0.83      0.75        24
         321       0.71      0.62      0.67         8
         322       1.00      1.00      1.00         2
         323       0.00      0.00      0.00         1
         324       0.94      0.88      0.91        77
         325       0.86      0.67      0.75        18
         327       0.25      0.25      0.25         4
         328       1.00      1.00      1.00         1
         329       0.00      0.00      0.00         1
         330       0.95      0.83      0.89        76
         331       0.80      0.80      0.80        20
         332       0.00      0.00      0.00         1
         333       0.98      0.80      0.88        51
         334       0.76      0.85      0.80        33
         335       0.50      0.57      0.53        21
         336       0.00      0.00      0.00         3
         337       0.00      0.00      0.00         1
         338       0.28      0.42      0.33        12
         339       1.00      0.75      0.86         4
         340       0.65      0.72      0.68        18
         341       0.91      0.97      0.94        30
         342       0.57      0.40      0.47        10
         343       0.81      0.68      0.74        19
         344       0.84      0.79      0.82        34
         345       0.85      0.85      0.85        20
         346       0.11      0.17      0.13         6
         347       0.80      0.94      0.86        50
         348       1.00      0.75      0.86        20
         349       0.55      0.55      0.55        11
         350       0.81      0.94      0.87        18
         351       1.00      1.00      1.00         1
         352       0.00      0.00      0.00         2
         354       0.75      0.60      0.67        10
         355       0.57      0.56      0.57        50
         356       0.60      0.75      0.67         4
         357       1.00      0.91      0.95        32
         358       0.00      0.00      0.00         3
         359       0.82      0.82      0.82        33
         360       0.67      0.55      0.60        11
         362       0.00      0.00      0.00         1
         363       0.00      0.00      0.00         1
         364       0.00      0.00      0.00         1
         365       0.91      0.94      0.93        33
         366       0.00      0.00      0.00         1
         367       0.92      0.90      0.91        77
         368       0.40      1.00      0.57         4
         369       1.00      0.67      0.80         3
         371       1.00      0.80      0.89         5
         372       0.88      0.78      0.82        18
         373       0.94      0.75      0.83        20
         375       1.00      0.67      0.80         3
         376       0.85      0.63      0.73        52
         379       1.00      0.67      0.80         3
         380       0.50      0.60      0.55         5
         381       0.70      0.66      0.68        77
         382       1.00      0.33      0.50         3
         383       0.70      0.70      0.70        10
         384       0.83      0.50      0.62        10
         386       0.43      0.30      0.35        10
         387       1.00      1.00      1.00         2
         388       0.00      0.00      0.00         1
         389       1.00      1.00      1.00         1
         390       1.00      0.62      0.76        13

In [ ]:
cm = confusion_matrix(y_test, y_pred)

print(cm.shape)

(621, 621)

In [ ]:
import joblib

joblib.dump(dt, "DecisionTree_Model.pkl")

print("Model Saved Successfully")

Model Saved Successfully

In [ ]:
results = pd.DataFrame({
    "Model":["Decision Tree"],
    "Accuracy":[accuracy],
    "Precision":[precision],
    "Recall":[recall],
    "F1 Score":[f1],
    "Training Time":[round(end-start,2)]
})

results

           Model  Accuracy  Precision    Recall  F1 Score  Training Time
0  Decision Tree  0.738833   0.747652  0.738833   0.73816           6.99